config/routes.rb
Rails.application.routes.draw do

  
  post 'favorites/:video/create' => 'favorites#create'
  post 'favorites/:video/destroy' => 'favorites#destroy'
  get 'sessions/new'
  get '/signup' => 'users#new'
  root 'home#index'
  get '/about' => 'home#about'
  get 'youtubes/index' 
  get 'youtubes/:video' => 'youtubes#show'
  post 'youtubes/:video' => 'microposts#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :video, presence: true

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy


  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save 
      flash[:success] = "コメントを作成しました。"
      redirect_to "/youtubes/#{@micropost.video}"
    else
      redirect_to "/youtubes/#{@micropost.video}"
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "コメントを削除しました。"
    redirect_to request.referrer || root_url
  end
  
   private
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
    
    def micropost_params
      params.require(:micropost).permit(:content,:user_id,:video)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
      <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/_micropost_form.html.erb
<% @micropost = Micropost.new unless @micropost %>
<%= form_for(@micropost, url: microposts_path) do |f| %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.hidden_field :video, value: @video_id %>
  </div>
  <%= f.submit "Post", class: "btn btn-defoult" %>
<% end %>