config/routes.rb
Rails.application.routes.draw do

  
  post 'favorites/:video/create' => 'favorites#create'
  post 'favorites/:video/destroy' => 'favorites#destroy'
  get 'sessions/new'
  get '/signup' => 'users#new'
  root 'home#index'
  get '/about' => 'home#about'
  get 'youtubes/index' 
  get 'youtubes/:video' => 'youtubes#show'
  post 'youtubes/:video' => 'microposts#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", 'https://github.com/YasudaGento/youtube_app' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <%= link_to("StreetDance" , "/", id:"logo") %>
      <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Home", root_path)%></li>
          <li><%= link_to("About","/about")%></li>
      <% if logged_in? %>
          <li><%= link_to("Videos","/youtubes/index")%></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
      </nav>
  
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <div class="container">
       <%= render 'layouts/header' %>
      　　<% flash.each do |message_type, message| %>
        　　<div class="alert alert-<%= message_type %>"><%= message %></div>
      　　<% end %>
    　　<%= yield %>
    </div>
    　　<%= render 'layouts/footer' %>
  </body>
</html>